#include <iostream>
#include <string>
#include <Windows.h>
#include <cstdlib>
#include <conio.h>
#include <vector>
#include <fstream>
#pragma once
#include "Void's.h"
#include "Date.h"
#include "Script.h"
#include "Cycle.h"